name: Android CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean project
      run: ./gradlew clean
      
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
      
    - name: Run unit tests
      run: ./gradlew test --stacktrace
      continue-on-error: true
      
    - name: Run lint
      run: ./gradlew lint --stacktrace
      continue-on-error: true
      
    - name: Upload build outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: app/build/outputs
        retention-days: 7
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 14
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          app/build/reports/tests/
          app/build/test-results/
        retention-days: 7
        
    - name: Upload lint results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lint-results
        path: app/build/reports/lint-results*.html
        retention-days: 7
        
    - name: Comment PR with results
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let comment = '## 🤖 CI Build Results\n\n';
          
          // Check if build succeeded
          comment += '### Build Status\n';
          comment += '✅ Build completed\n\n';
          
          // Add artifact links
          comment += '### 📦 Artifacts\n';
          comment += '- APK: Available in workflow artifacts\n';
          comment += '- Test Results: Available in workflow artifacts\n';
          comment += '- Lint Report: Available in workflow artifacts\n\n';
          
          comment += '_Generated by GitHub Actions_';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

